# yaml-language-server: $schema=../schemas/site.json
url: "https://ambagi.pages.dev"
title: "Ambagi"
description: "Ambagi senza pretese"
author: "F."
language: "it"
keywords: []
resources:
  fonts:
    logo: "Tangerine-Bold.woff2"
    head: "Afacad-Bold.woff2"
    subhead: "Afacad-SemiBoldItalic.woff2"
    bodyNorm: "Sanchez-Regular.woff2"
    bodyEmph: "Sanchez-Italic.woff2"
  icons:
    loading: "loading.svg"
    videoLoading: "loading.svg"
  scripts:
    page: "page.ts"
    home: "home.ts"
  styles:
    page: "page.sass"
    home: "home.sass"
    noscript: "noscript.sass"
  favicon: "favicon.svg"
